/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlaceholderRouteImport } from './routes/placeholder'
import { Route as KdmRouteImport } from './routes/kdm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaceholderIndexRouteImport } from './routes/placeholder.index'
import { Route as KdmIndexRouteImport } from './routes/kdm.index'
import { Route as PlaceholderDocsRouteImport } from './routes/placeholder.docs'
import { Route as KdmDocsRouteImport } from './routes/kdm.docs'
import { Route as PlaceholderDocsIndexRouteImport } from './routes/placeholder.docs.index'
import { Route as KdmDocsIndexRouteImport } from './routes/kdm.docs.index'
import { Route as PlaceholderDocsSlugRouteImport } from './routes/placeholder.docs.$slug'
import { Route as KdmDocsSlugRouteImport } from './routes/kdm.docs.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholderRoute = PlaceholderRouteImport.update({
  id: '/placeholder',
  path: '/placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const KdmRoute = KdmRouteImport.update({
  id: '/kdm',
  path: '/kdm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholderIndexRoute = PlaceholderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaceholderRoute,
} as any)
const KdmIndexRoute = KdmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KdmRoute,
} as any)
const PlaceholderDocsRoute = PlaceholderDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PlaceholderRoute,
} as any)
const KdmDocsRoute = KdmDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => KdmRoute,
} as any)
const PlaceholderDocsIndexRoute = PlaceholderDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaceholderDocsRoute,
} as any)
const KdmDocsIndexRoute = KdmDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KdmDocsRoute,
} as any)
const PlaceholderDocsSlugRoute = PlaceholderDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaceholderDocsRoute,
} as any)
const KdmDocsSlugRoute = KdmDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KdmDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kdm': typeof KdmRouteWithChildren
  '/placeholder': typeof PlaceholderRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/kdm/docs': typeof KdmDocsRouteWithChildren
  '/placeholder/docs': typeof PlaceholderDocsRouteWithChildren
  '/kdm/': typeof KdmIndexRoute
  '/placeholder/': typeof PlaceholderIndexRoute
  '/kdm/docs/$slug': typeof KdmDocsSlugRoute
  '/placeholder/docs/$slug': typeof PlaceholderDocsSlugRoute
  '/kdm/docs/': typeof KdmDocsIndexRoute
  '/placeholder/docs/': typeof PlaceholderDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/kdm': typeof KdmIndexRoute
  '/placeholder': typeof PlaceholderIndexRoute
  '/kdm/docs/$slug': typeof KdmDocsSlugRoute
  '/placeholder/docs/$slug': typeof PlaceholderDocsSlugRoute
  '/kdm/docs': typeof KdmDocsIndexRoute
  '/placeholder/docs': typeof PlaceholderDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kdm': typeof KdmRouteWithChildren
  '/placeholder': typeof PlaceholderRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/kdm/docs': typeof KdmDocsRouteWithChildren
  '/placeholder/docs': typeof PlaceholderDocsRouteWithChildren
  '/kdm/': typeof KdmIndexRoute
  '/placeholder/': typeof PlaceholderIndexRoute
  '/kdm/docs/$slug': typeof KdmDocsSlugRoute
  '/placeholder/docs/$slug': typeof PlaceholderDocsSlugRoute
  '/kdm/docs/': typeof KdmDocsIndexRoute
  '/placeholder/docs/': typeof PlaceholderDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kdm'
    | '/placeholder'
    | '/privacy'
    | '/terms'
    | '/kdm/docs'
    | '/placeholder/docs'
    | '/kdm/'
    | '/placeholder/'
    | '/kdm/docs/$slug'
    | '/placeholder/docs/$slug'
    | '/kdm/docs/'
    | '/placeholder/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/kdm'
    | '/placeholder'
    | '/kdm/docs/$slug'
    | '/placeholder/docs/$slug'
    | '/kdm/docs'
    | '/placeholder/docs'
  id:
    | '__root__'
    | '/'
    | '/kdm'
    | '/placeholder'
    | '/privacy'
    | '/terms'
    | '/kdm/docs'
    | '/placeholder/docs'
    | '/kdm/'
    | '/placeholder/'
    | '/kdm/docs/$slug'
    | '/placeholder/docs/$slug'
    | '/kdm/docs/'
    | '/placeholder/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KdmRoute: typeof KdmRouteWithChildren
  PlaceholderRoute: typeof PlaceholderRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder': {
      id: '/placeholder'
      path: '/placeholder'
      fullPath: '/placeholder'
      preLoaderRoute: typeof PlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kdm': {
      id: '/kdm'
      path: '/kdm'
      fullPath: '/kdm'
      preLoaderRoute: typeof KdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder/': {
      id: '/placeholder/'
      path: '/'
      fullPath: '/placeholder/'
      preLoaderRoute: typeof PlaceholderIndexRouteImport
      parentRoute: typeof PlaceholderRoute
    }
    '/kdm/': {
      id: '/kdm/'
      path: '/'
      fullPath: '/kdm/'
      preLoaderRoute: typeof KdmIndexRouteImport
      parentRoute: typeof KdmRoute
    }
    '/placeholder/docs': {
      id: '/placeholder/docs'
      path: '/docs'
      fullPath: '/placeholder/docs'
      preLoaderRoute: typeof PlaceholderDocsRouteImport
      parentRoute: typeof PlaceholderRoute
    }
    '/kdm/docs': {
      id: '/kdm/docs'
      path: '/docs'
      fullPath: '/kdm/docs'
      preLoaderRoute: typeof KdmDocsRouteImport
      parentRoute: typeof KdmRoute
    }
    '/placeholder/docs/': {
      id: '/placeholder/docs/'
      path: '/'
      fullPath: '/placeholder/docs/'
      preLoaderRoute: typeof PlaceholderDocsIndexRouteImport
      parentRoute: typeof PlaceholderDocsRoute
    }
    '/kdm/docs/': {
      id: '/kdm/docs/'
      path: '/'
      fullPath: '/kdm/docs/'
      preLoaderRoute: typeof KdmDocsIndexRouteImport
      parentRoute: typeof KdmDocsRoute
    }
    '/placeholder/docs/$slug': {
      id: '/placeholder/docs/$slug'
      path: '/$slug'
      fullPath: '/placeholder/docs/$slug'
      preLoaderRoute: typeof PlaceholderDocsSlugRouteImport
      parentRoute: typeof PlaceholderDocsRoute
    }
    '/kdm/docs/$slug': {
      id: '/kdm/docs/$slug'
      path: '/$slug'
      fullPath: '/kdm/docs/$slug'
      preLoaderRoute: typeof KdmDocsSlugRouteImport
      parentRoute: typeof KdmDocsRoute
    }
  }
}

interface KdmDocsRouteChildren {
  KdmDocsSlugRoute: typeof KdmDocsSlugRoute
  KdmDocsIndexRoute: typeof KdmDocsIndexRoute
}

const KdmDocsRouteChildren: KdmDocsRouteChildren = {
  KdmDocsSlugRoute: KdmDocsSlugRoute,
  KdmDocsIndexRoute: KdmDocsIndexRoute,
}

const KdmDocsRouteWithChildren =
  KdmDocsRoute._addFileChildren(KdmDocsRouteChildren)

interface KdmRouteChildren {
  KdmDocsRoute: typeof KdmDocsRouteWithChildren
  KdmIndexRoute: typeof KdmIndexRoute
}

const KdmRouteChildren: KdmRouteChildren = {
  KdmDocsRoute: KdmDocsRouteWithChildren,
  KdmIndexRoute: KdmIndexRoute,
}

const KdmRouteWithChildren = KdmRoute._addFileChildren(KdmRouteChildren)

interface PlaceholderDocsRouteChildren {
  PlaceholderDocsSlugRoute: typeof PlaceholderDocsSlugRoute
  PlaceholderDocsIndexRoute: typeof PlaceholderDocsIndexRoute
}

const PlaceholderDocsRouteChildren: PlaceholderDocsRouteChildren = {
  PlaceholderDocsSlugRoute: PlaceholderDocsSlugRoute,
  PlaceholderDocsIndexRoute: PlaceholderDocsIndexRoute,
}

const PlaceholderDocsRouteWithChildren = PlaceholderDocsRoute._addFileChildren(
  PlaceholderDocsRouteChildren,
)

interface PlaceholderRouteChildren {
  PlaceholderDocsRoute: typeof PlaceholderDocsRouteWithChildren
  PlaceholderIndexRoute: typeof PlaceholderIndexRoute
}

const PlaceholderRouteChildren: PlaceholderRouteChildren = {
  PlaceholderDocsRoute: PlaceholderDocsRouteWithChildren,
  PlaceholderIndexRoute: PlaceholderIndexRoute,
}

const PlaceholderRouteWithChildren = PlaceholderRoute._addFileChildren(
  PlaceholderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KdmRoute: KdmRouteWithChildren,
  PlaceholderRoute: PlaceholderRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
